name: streamit_flutter
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  nb_utils: ^4.2.10
  html: 0.15.0
  google_fonts: 2.1.0
  http: 0.13.3
  url_launcher: ^6.0.2
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  animations: ^2.0.0
  package_info: ^2.0.2
  intl: ^0.17.0
  flutter_widget_from_html: ^0.6.1
  cached_network_image: ^3.0.0
  flutter_inappwebview: ^5.3.2
  flutter_rating_bar: ^4.0.0
  google_mobile_ads: ^0.13.0
  onesignal_flutter: ^3.0.0-beta4

  image_picker: ^0.8.0
  video_player: ^2.1.4

  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.4
  #flutter packages pub run build_runner build

  flutter_localizations:
    sdk: flutter

dependency_overrides:
#video_player: "1.0.1"
#webview_flutter: ^1.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/items/home/favorite/
    - assets/items/home/
    - assets/items/home/suggested/
    - assets/items/home/trending/
    - assets/items/home/upcoming/
    - assets/items/movies/
    - assets/items/movies/poster_ek42.png
    - assets/items/shows/
    - assets/items/actors/
    - assets/items/episodes/
    - assets/icons/ic_fb.png
    - assets/icons/ic_google.png
    - assets/images/background_ek35.png
    - assets/gif/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: assets/fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/googlesansebold.ttf
